### ISSUE TITLE
Achievement Typo in index.js

### ISSUE THREAD

**Issue by Deiru** [codingMASTER398/Dodecadone-Steam#1]
Heya,

Looks like you made a bit of a typo on Line 893 of src/index.js - The trait reads as `survivalOfTheFittest` and should read as `doctor` I believe, while the achievement on line 896 should read as `survivalOfTheFittest` not `againstAllOdds`.

Nothing serious lol, just yeah - the achievement on Steam doesn't work because of it. Hope this helps!

**Comment by codingMASTER398** [comment]
Thanks for pointing that out! Will fix soon
